from enum import Enum


class AgentState(str, Enum):
    IDLE = "IDLE"
    PLANNING = "PLANNING"
    CLONING = "CLONING"
    ANALYZING = "ANALYZING"
    RUNNING_TESTS = "RUNNING_TESTS"
    OBSERVING = "OBSERVING"
    ANALYZING_FAILURE = "ANALYZING_FAILURE"
    ROOT_CAUSE_FOUND = "ROOT_CAUSE_FOUND"
    FIXING = "FIXING"
    RETESTING = "RETESTING"
    REFLECTING = "REFLECTING"
    CORRECTING = "CORRECTING"
    COMPLETED = "COMPLETED"
    SUCCESS = "COMPLETED"
    FAILED = "FAILED"
    HUMAN_INTERVENTION = "HUMAN_INTERVENTION"
